name: FixTorchDrop
description: Fix redstone torches dropping when block updates occur and dependent blocks are not loaded.
version: %VERSION%
depend: [MessageManager]
author: EdGruberman (ed@rjump.com)
main: edgruberman.bukkit.fixtorchdrop.Main
