name: FixTorchDrop
description: Fix redstone torches dropping when block updates occur and attached block is not loaded
version: %VERSION%
depend: [MessageManager]
author: EdGruberman (ed@rjump.com)
main: edgruberman.bukkit.fixtorchdrop.Main
